import { Navbar, SidebarLeft, SidebarRight } from "@components";
import "@styles/globals.css";
import dynamic from 'next/dynamic';
import ClientOnly from "@/components/ClientOnly";
import SessionExpiryDialogWrapper from "@/components/SessionExpiryDialogWrapper";
import { Toaster } from "react-hot-toast";

const ChatBotWidget = dynamic(() => import('@/components/ChatBotWidget'), {
  ssr: false,
});

export const metadata = {
  title: "Facebook",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-[#e9ebee] relative">
        <Navbar />
        <div className="flex justify-center relative">
          <SidebarLeft />
          {children}
          <ClientOnly>
            <SessionExpiryDialogWrapper />
            <ChatBotWidget />
            <Toaster />
          </ClientOnly>
          <SidebarRight />
        </div>
      </body>
    </html>
  );
}
